# Site settings
title: chutra.org
motto: Hi! - I'm Meriton, a programmer and aviation ethusiast.
email: meriton@chutra.org
description: > # this means to ignore newlines until "baseurl:"
  A programmer blog, about well you know, programming and the occasional aviation travel tips.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chutra.org" # the base hostname & protocol for your site
twitter_username: mrchutra
github_username:  meriton

# Build settings
markdown: kramdown
